- name: make a local directory for bare repos
  file:
    path: /home/{{ opa_bash_user }}/bare
    state: directory

- name: make a bare origin km_bash repo
  synchronize:
    src: '{{ km_bash_local_repo }}'
    dest: /home/{{ opa_bash_user }}/bare

- name: checkout km_bash
  git:
    repo: /home/{{ opa_bash_user }}/bare/km_bash.git
    dest: /home/{{ opa_bash_user }}/.opa_bash/users/mccullok/km_bash

- name: make a bare origin myvim repo
  synchronize:
    src: '{{ myvim_local_repo }}'
    dest: /home/{{ opa_bash_user }}/bare

- name: checkout myvim
  git:
    repo: /home/{{ opa_bash_user }}/bare/myvim.git
    dest: /home/{{ opa_bash_user }}/.opa_bash/users/mccullok/myvim

- name: sync vim plugins
  synchronize:
    src: '{{ myvim_local_bundle }}'
    dest: /home/{{ opa_bash_user }}/.opa_bash/users/mccullok/myvim/vim

- name: put my .bash_profile in place
  template:
    src: bash_profile.j2
    dest: ~/.opa_bash/users/mccullok/.bash_profile
